---
title: Operator (StreamDeck)
---
graph TB
    subgraph c5["Ejection"]
        Net["Net
             Algae"]
        EjectAlg["Eject
                  Algae"]
        EjectCoral["Eject
                    Coral"]
    end
    subgraph c4["Intake"]
        r1c4["Not
              Assigned"]
            style r1c4 color:#caa
        IntakeAlg["Algae
                   Intake"]
        IntakeGrd["Coral
                   Ground Intake"]
    end
    subgraph c3["Reef (Other)"]
        RmAlgU["Algae
                (Upper)"]
        RmAlgL["Algae
                (Lower)"]
        Trough["Align
                Trough"]
    end
    subgraph c1c2["Reef (Pegs)"]
        LL4["L4\n(Left)"]~~~RL4["L4\n(Right)"]
        LL3["L3\n(Left)"]~~~RL3["L3\n(Right)"]
        LL2["L2\n(Left)"]~~~RL2["L2\n(Right)"]
    end