---
title: Subsystem Architecture
---
flowchart TD
    Robot-->
        LED
    Robot-->
        Drivetrain-->
            SwerveModules
    Robot-->
    %%Scoring outline may change in the future
        Scorer-->
            Elevator
        Scorer-->
            Arm-->
                Pivot
            Arm-->
                Placer
    Robot-->
        Indexer
    Robot-->
        Intake-->
            IntakePivot
        Intake-->
            IntakeMotors