---
title: Subsystem Architecture
---
flowchart TD
    Robot-->
        LED
    Robot-->
        Drivetrain
    Robot-->
        Scorer-->
            Elevator
        Scorer-->
            Arm-->
                Pivot
            Arm-->
                Placer
    Robot-->
        Intake