---
title: Stream Deck Layout
---
graph TB
%% @backgroundColor(#202020)

    streamdeck(("Stream Deck"))
    autoAlign(("Auto Align"))
    elevator(("Elevator"))
    pivot(("Pivot to Reef"))
    chute(("Chute Intake"))
    chuteAdjust(("Adjust to Chute Intake"))
    chutePivot(("Chute Pivot"))
    chuteElevator(("Chute Elevator"))

    streamdeck---|idle|streamdeck
    streamdeck---|L2|autoAlign
    streamdeck---|L3|autoAlign
    streamdeck---|L4|autoAlign
    streamdeck---|R2|autoAlign
    streamdeck---|R3|autoAlign
    streamdeck---|R4|autoAlign
    autoAlign---|align|autoAlign
    autoAlign~~~elevator
    elevator~~~pivot
    streamdeck-.-elevator
    streamdeck-.-pivot
    elevator-.-LNoteLayer(["auto align, pivot to reef,
                and elevator simultaneously"])-.-pivot

    linkStyle default stroke:white
    linkStyle 8 stroke:white,stroke-width:2px,stroke-dasharray:3;
    linkStyle 9 stroke:white,stroke-width:2px,stroke-dasharray:3;
    linkStyle 10 stroke:white,stroke-width:2px,stroke-dasharray:3;
    linkStyle 11 stroke:white,stroke-width:2px,stroke-dasharray:3;
    linkStyle 12 stroke:white,stroke-width:2px,stroke-dasharray:3;
    linkStyle 13 stroke:white,stroke-width:2px,stroke-dasharray:3;
    %% TODO: please make line coloring more efficient, do not know the best way to do this